#define SERVO_PIN 3
#define LED_PIN 4
#define TEMP_PIN 5
#define RTC_CLK_PIN 6
#define RTC_DAT_PIN 7
#define RTC_RST_PIN 8
#define BUTTON_PIN 9
#define TDS_PIN A0
#define POTENTIO_PIN A1
#define LDR_PIN A2
